theme: jekyll-theme-slate
title: Interspeech 2023 Special Session on Invariant and Robust Pretrained Acoustic Models
description: Interspeech 2023 Special Session on Invariant and Robust Pretrained Acoustic Models
email: irpam2023@gmail.com
